---

# tasks file for create_instances
- name: Launching the Webservers EC2 instances on AWS
  ec2:
    region: "ap-south-1"
    image: "ami-052c08d70def0ac62"
    instance_type: "t2.micro"
    count: 2
    vpc_subnet_id: "{{ subnet }}"
    group_id: "{{ sg }}"
    instance_tags:
      Name: "webserver"
    key_name: "{{ key }}"
    assign_public_ip: yes
    state: present
    wait: yes
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
  register: webserver_logs

- name: Launching the Load Balancer EC2 instance on AWS
  ec2:
    region: "ap-south-1"
    image: "ami-052c08d70def0ac62"
    instance_type: "t2.micro"
    count: 1
    vpc_subnet_id: "{{ subnet }}"
    group_id: "{{ sg }}"
    instance_tags:
      Name: "loadbalancer"
    key_name: "{{ key }}"
    assign_public_ip: yes
    state: present
    wait: yes
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
  register: loadbalancer_log

- debug:
     var: webserver_logs
- debug:
     var: loadbalancer_log
